CREATE TABLE [dbo].[я_счф] (
  [счф_код] [int] NOT NULL,
  [счф_док] [int] NULL,
  [счф_дата] [date] NULL,
  [счф_сум] [numeric](12, 2) NULL,
  [счф_ном] [int] NULL,
  [счф_сут] [numeric](5, 1) NULL,
  [опл_дата] [date] NULL,
  [опл_док] [varchar](50) NULL,
  [счф_цена] [numeric](12, 2) NULL,
  [счф_инф] [varchar](50) NULL,
  [дата_с] [date] NULL,
  [дата_по] [date] NULL,
  [счф_ски] [numeric](12, 2) NULL,
  [счф_итого] [numeric](12, 2) NULL,
  [дог_код] [int] NULL,
  [дог_дата] [date] NULL,
  [дог_ном] [bigint] NULL,
  [дог_с] [date] NULL,
  [дог_по] [date] NULL,
  [дог_хоз] [int] NULL,
  [дог_орг] [int] NULL,
  [дог_вид_код] [int] NULL,
  [дог_ски] [int] NULL,
  [дог_сумма] [numeric](18, 2) NULL,
  [дог_инф] [varchar](300) NULL,
  [сум_итого_про] [varchar](800) NULL,
  [зак_код] [int] NULL,
  [зак_имя] [varchar](300) NULL,
  [зак_имя_пол] [varchar](500) NULL,
  [зак_имя_кор] [varchar](300) NULL,
  [зак_преамбула] [varchar](1000) NULL,
  [зак_дейст_на_осн] [varchar](100) NULL,
  [зак_рук_должность] [varchar](100) NULL,
  [зак_рук_фио_пол] [varchar](100) NULL,
  [зак_рук_фио_кор] [varchar](100) NULL,
  [зак_счет_номер] [char](30) NULL,
  [зак_счет_мфо] [char](30) NULL,
  [зак_счет_банк] [char](30) NULL,
  [зак_унп] [char](15) NULL,
  [зак_город] [varchar](50) NULL,
  [зак_адрес] [varchar](500) NULL,
  [зак_тел_рук] [char](50) NULL,
  [зак_контакт_фио] [char](30) NULL,
  [зак_тел_контакт] [char](50) NULL,
  [зак_тел_факс] [char](15) NULL,
  [хоз_код] [int] NULL,
  [хоз_имя] [char](50) NULL,
  [хоз_имя_1] [char](50) NULL,
  [хоз_имя_2] [char](50) NULL,
  [хоз_имя_3] [char](50) NULL,
  [хоз_имя_4] [char](50) NULL,
  [хоз_имя_пол] [char](150) NULL,
  [хоз_имя_кор] [varchar](50) NULL,
  [хоз_преамбула] [varchar](300) NULL,
  [хоз_счет_номер] [char](30) NULL,
  [хоз_счет_мфо] [char](10) NULL,
  [хоз_счет_банк] [char](30) NULL,
  [хоз_счет_банк_адр] [char](100) NULL,
  [хоз_банк_унп] [char](10) NULL,
  [хоз_унп] [char](10) NULL,
  [хоз_адрес] [char](50) NULL,
  [хоз_страна] [char](30) NULL,
  [хоз_рук_фио_кор] [char](30) NULL,
  [хоз_рук_фио_пол] [char](50) NULL,
  [хоз_рук_должность] [char](30) NULL,
  [хоз_дейст_на_осн] [varchar](100) NULL,
  [хоз_тел] [char](30) NULL,
  [хоз_факс] [char](30) NULL
)
ON [PRIMARY]
GO