CREATE TABLE [dbo].[я_нач_акт] (
  [счет_код] [int] NULL,
  [счет_имя] [varchar](300) NULL,
  [док] [int] NULL,
  [дата] [date] NULL,
  [инф_счет] [text] NULL,
  [орг_хоз_код] [int] NULL,
  [орг_код] [int] NULL,
  [орг_имя] [varchar](300) NULL,
  [зак_имя] [varchar](300) NULL,
  [зак_имя_пол] [varchar](1000) NULL,
  [зак_имя_кор] [varchar](1000) NULL,
  [зак_преамбула] [varchar](1000) NULL,
  [зак_дейст_на_осн] [varchar](500) NULL,
  [зак_счет_номер] [char](30) NULL,
  [зак_счет_мфо] [char](30) NULL,
  [зак_счет_банк] [char](30) NULL,
  [зак_унп] [char](15) NULL,
  [зак_город] [varchar](50) NULL,
  [зак_адрес] [varchar](500) NULL,
  [зак_рук_должность] [varchar](200) NULL,
  [зак_рук_фио_пол] [varchar](50) NULL,
  [зак_рук_фио_кор] [varchar](50) NULL,
  [хоз_имя] [char](50) NULL,
  [хоз_имя_1] [char](50) NULL,
  [хоз_имя_2] [char](50) NULL,
  [хоз_имя_3] [char](50) NULL,
  [хоз_имя_4] [char](50) NULL,
  [хоз_имя_пол] [char](150) NULL,
  [хоз_имя_кор] [varchar](50) NULL,
  [хоз_счет_номер] [char](30) NULL,
  [хоз_счет_мфо] [char](10) NULL,
  [хоз_счет_банк] [char](30) NULL,
  [хоз_счет_банк_адр] [char](100) NULL,
  [хоз_банк_унп] [char](10) NULL,
  [хоз_унп] [char](10) NULL,
  [хоз_адрес] [char](50) NULL,
  [хоз_страна] [char](30) NULL,
  [хоз_рук_фио_кор] [char](30) NULL,
  [хоз_рук_фио_пол] [char](50) NULL,
  [хоз_рук_должность] [char](30) NULL,
  [хоз_дейст_на_осн] [varchar](100) NULL,
  [хоз_тел] [char](30) NULL,
  [хоз_факс] [char](30) NULL,
  [преамбула] [varchar](1000) NULL,
  [скидка] [varchar](300) NULL,
  [стоим] [varchar](800) NULL,
  [предолата] [varchar](800) NULL,
  [сум_пропись] [varchar](255) NULL,
  [сут_сум] [numeric](4, 1) NULL,
  [ски_сум] [numeric](12, 2) NULL,
  [нач_сум] [numeric](12, 2) NULL,
  [кли_код] [int] NULL,
  [дата_зае] [datetime] NULL,
  [дата_вые] [datetime] NULL,
  [сут] [numeric](38, 1) NULL,
  [телефоны] [varchar](1000) NULL,
  [гра_пол] [char](100) NULL,
  [гра_стр] [char](100) NULL,
  [граж_срок] [char](100) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO