CREATE TABLE [dbo].[орг_хоз] (
  [орг_код] [int] IDENTITY,
  [орг_имя] [char](50) NULL,
  [орг_имя_1] [char](50) NULL,
  [орг_имя_2] [char](50) NULL,
  [орг_имя_3] [char](50) NULL,
  [орг_имя_4] [char](50) NULL,
  [орг_имя_пол] [char](150) NULL,
  [орг_имя_кор] [char](50) NULL,
  [счет_номер] [char](30) NULL,
  [счет_банк] [char](30) NULL,
  [счет_банк_адр] [char](100) NULL,
  [счет_банк_унп] [char](10) NULL,
  [унп] [char](10) NULL,
  [адрес] [char](50) NULL,
  [страна] [char](30) NULL,
  [рук_фио_кор] [char](30) NULL,
  [рук_фио_пол] [char](50) NULL,
  [рук_должность] [char](30) NULL,
  [дейст_на_осн] [varchar](100) NULL,
  [тел] [char](30) NULL,
  [факс] [char](30) NULL,
  [преамбула] [varchar](300) NULL,
  [счет_мфо] [char](10) NULL,
  [счет_номер_RUR] [char](30) NULL,
  [счет_банк_RUR] [char](30) NULL,
  [счет_мфо_RUR] [char](10) NULL,
  [счет_банк_адр_RUR] [char](100) NULL,
  [счет_номер_EUR] [char](30) NULL,
  [счет_банк_EUR] [char](30) NULL,
  [счет_мфо_EUR] [char](10) NULL,
  [счет_банк_адр_EUR] [char](100) NULL,
  [показывать] [int] NULL,
  CONSTRAINT [PK_c_орг_хоз] PRIMARY KEY CLUSTERED ([орг_код])
)
ON [PRIMARY]
GO