CREATE TABLE [dbo].[кли] (
  [кли_код] [int] IDENTITY,
  [кли_код_был] [int] NULL,
  [фам] [char](30) NULL,
  [имя] [char](30) NULL,
  [ФИО] AS ((((rtrim(isnull([фам],''))+' ')+rtrim(isnull([имя],'')))+' ')+rtrim(isnull([отч],''))),
  [отч] [char](30) NULL,
  [пол] [int] NULL CONSTRAINT [DF_кли_пол] DEFAULT (1),
  [рожд_дата] [date] NULL,
  [рожд_место] [char](30) NULL,
  [гражд_код] [int] NULL CONSTRAINT [DF_кли_гражд_код] DEFAULT (1),
  [рег] [int] NULL CONSTRAINT [DF_кли_рег] DEFAULT (0),
  [раб_место] [char](30) NULL,
  [раб_должность] [char](30) NULL,
  [раб_ком_уд] [char](30) NULL,
  [раб_прибыл] [char](30) NULL,
  [пас_вид_код] [int] NULL CONSTRAINT [DF_кли_пас_вид_код] DEFAULT (1),
  [пас_номер] [char](30) NULL,
  [пас_дата] [date] NULL,
  [пас_выдан] [char](30) NULL,
  [адр_страна_код] [int] NULL CONSTRAINT [DF_кли_адр_страна_код] DEFAULT (1),
  [адр_город] [char](30) NULL,
  [адрес] [char](100) NULL,
  [телефон] [char](30) NULL,
  [е_маил] [char](30) NULL,
  [авто_марка] [char](30) NULL,
  [авто_номер] [char](30) NULL,
  [инф_кли] [text] NULL,
  [виза_вид_код] [int] NULL,
  [виза_сер] [char](3) NULL CONSTRAINT [DF_кли_виза_сер] DEFAULT ('BLR'),
  [виза_номер] [char](30) NULL,
  [виза_дата_с] [date] NULL,
  [виза_дата_по] [date] NULL,
  [страх_стр_код] [int] NULL,
  [страх_кем_код] [int] NULL,
  [страх_номер] [char](30) NULL,
  [страх_дата_с] [date] NULL,
  [страх_дата_по] [date] NULL,
  [миг_карта] [char](30) NULL,
  [миг_карта_дата_с] [date] NULL,
  [миг_карта_дата_по] [date] NULL,
  [скид_карта] [char](30) NULL,
  [скид_проц] [int] NULL,
  [гра_дата] [date] NULL,
  [гра_код] [int] NULL,
  [фам_лат] [char](30) NULL,
  [имя_лат] [char](30) NULL,
  [отч_лат] [char](30) NULL,
  [дата_соз] [datetime] NULL,
  [дата_изм] [datetime] NULL,
  [пас_дата_по] [date] NULL,
  CONSTRAINT [PK_кли] PRIMARY KEY CLUSTERED ([кли_код]),
  CONSTRAINT [FK_кли_кли_виза_вид] FOREIGN KEY ([виза_вид_код]) REFERENCES [dbo].[кли_виза_вид] ([виза_вид_код]),
  CONSTRAINT [FK_кли_кли_пас_вид] FOREIGN KEY ([пас_вид_код]) REFERENCES [dbo].[кли_пас_вид] ([пас_вид_код]),
  CONSTRAINT [FK_кли_кли_страх_кем] FOREIGN KEY ([страх_кем_код]) REFERENCES [dbo].[кли_страх_кем] ([страх_кем_код])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO